
# This is a base image
# we can see images on docker hub
FROM node:alpine


# copies everythin in this directory into the /app directory in the container
COPY . /app

# moves us to the app directory, works like the cd command
WORKDIR /app

CMD node app.js 